### ISSUE TITLE
Adele - 25 got merged into Adele - 21 - last.fm search response only has summary - no tracks

### ISSUE THREAD

**Issue by sa2000a** [plexinc-agents/LastFM.bundle#18]
Should have created a separate Album when scanning `Adele - 25` album folder. Instead it merged the tracks into the Adele 21 album and also updated release date and poster of Adele 21 with info for Adele 25

Query http://lastfm-z.plexapp.com/2.0/?method=album.getInfo&artist=adele&album=25&autocorrect=1&lang=en&format=json&api_key=d5310352469c2631e5976d0f4a599773 returned this response:

https://gist.github.com/sa2000a/44fbfa55ff7b5909a5c6

Log File here
https://gist.github.com/sa2000a/44fbfa55ff7b5909a5c6#file-com-plexapp-agents-lastfm_2015-11-20_145757-log

PMS running 0.9.14.1
Windows 7

Screenshot of Adele 21 merging Album 25 tracks
![image](https://cloud.githubusercontent.com/assets/6320013/11324175/3a793086-9122-11e5-827a-deeb9d598dd2.png)

**Comment by sandman4sure** [comment]
When adding `25` last.fm will see it as being the `21` album. The bundle which gets created is `Adele/21`
If we only have this album and checked `Use embedded tags` you wouldn't notice, because it will take the name of the album from the music files instead of last.fm.
When we have both albums available however (21 and 25), they get one bundle file and one name for the album.

The problem here is that last.fm thinks it's `21` and not `25`. Probably due to the similarity in album names and the fact that the `25` album has little data on last.fm (no tack information)

**Comment by maxGreenblatt** [comment]
Closing in favor of issue created above.
